config/routes.rb
Methodicomic::Application.routes.draw do
  get "issues/list"
  get "issues/:id/view" => 'issues#view', as: 'issues_view'
  get "issues/:id/read" => 'issues#toggle_read', as: 'issues_read'
  get "issues/:id/read_next" => 'issues#read_next', as: 'issues_next_read'
  get "issues/:id/acquire" => 'issues#toggle_acquired', as: 'issues_acquire'
  get "issues/:id/track" => 'issues#toggle_track', as: 'issues_track'
  get "issues/unread"
  get "issues/unacquired"
  get "issues/search_by_writer"
  get "issues/search_by_series_and_writer"
  post "issues/set" => 'issues#batch_set', as: 'issues_set'
  get "series/search"
  get "series/list"
  get "series/:id/view" => 'series#view', as: 'series_view'
  get "series/:id/follow" => 'series#follow', as: 'series_follow'
  get "series/:id/unfollow" => 'series#unfollow', as: 'series_unfollow'
  get "session/create"
  get "welcome/index"
  get "welcome/login"
  match '/auth/:provider/callback', to: 'session#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'session#destroy', as: 'signout', via: [:get, :post]

  root 'welcome#index'

end

app/models/gcd/gcd_series.rb
module GCD
  class GcdSeries < ActiveRecord::Base
    self.table_name = 'gcd_series'
    self.inheritance_column = 'ruby_type'
    self.primary_key = 'id'

    if ActiveRecord::VERSION::STRING < '4.0.0' || defined?(ProtectedAttributes)
      attr_accessible :name, :sort_name, :format, :year_began, :year_began_uncertain, :year_ended, :year_ended_uncertain, :publication_dates, :first_issue_id, :last_issue_id, :is_current, :publisher_id, :country_id, :language_id, :tracking_notes, :notes, :publication_notes, :has_gallery, :open_reserve, :issue_count, :created, :modified, :reserved, :deleted, :has_indicia_frequency, :has_isbn, :has_barcode, :has_issue_title, :has_volume, :is_comics_publication, :color, :dimensions, :paper_stock, :binding, :publishing_format, :has_rating
    end

    has_many :issues, class_name: 'GcdIssue', foreign_key: 'series_id', inverse_of: :series
    has_many :user_series, foreign_key: 'series_id'
    has_many :tracking_users, through: :user_series, class_name: 'User'
    belongs_to :publisher, class_name: 'GcdPublisher', foreign_key: 'publisher_id'
    belongs_to :language, class_name: 'GcdLanguage', foreign_key: 'language_id'
    belongs_to :country, class_name: 'GcdCountry', foreign_key: 'country_id'
    #has_and_belongs_to_many :users, class_name: 'User', join_table: 'gcd_series_users'
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  def list
  end
  def search_by_writer
    @series = {}
    if params[:page]
      @issues = GCD::GcdIssue.joins(:stories).includes(:series).where('script like ?', "%#{params[:q]}%").distinct(:issue_id).page(params[:page])
    else
      @issues = GCD::GcdIssue.joins(:stories).includes(:series).where('script like ?', "%#{params[:q]}%").distinct(:issue_id)
      @issues.each do |issue|
        @series[issue.series] = 0 unless @series[issue.series]
        @series[issue.series] += 1
      end
      @series = @series.sort_by{|k, v| -v} # sort by descending number of issues by this writer
      @issues = GCD::GcdIssue.joins(:stories).includes(:series).where('script like ?', "%#{params[:q]}%").distinct(:issue_id).page(params[:page]) # now bring just one page

    end
  end
  def search_by_series_and_writer
    @issues = GCD::GcdIssue.joins(:stories, :series).includes(:series).where(series_id: params[:series]).where('script like ?', "%#{params[:writer]}%").distinct(:issue_id)
    @series = GCD::GcdSeries.find(params[:series])
  end
  def unread
    unless current_user.nil?
      @issues = current_user.unread_issues.page params[:page]
    else
      redirect_to root_url, :flash => {:error => 'Must be logged in'}
    end
  end
  def unacquired
    unless current_user.nil?
      @issues = current_user.unacquired_issues.page params[:page]
    else
      redirect_to root_url, :flash => {:error => 'Must be logged in'}
    end
  end
  def view
    @issue = GCD::GcdIssue.find(params[:id])
    if @issue.nil?
      redirect_to root_url, :flash => {:error => 'No such issue'}
    end
  end

  def read_next
    if do_toggle_read
      @series = @issue.tracked_issue.series # grab series from previous issue
      @issue = current_user.unread_for_series(@series).first # this should now be the *next* issue to read, now that we've marked this one as read
      respond_to do |format|
        format.js # AJAX
      end
    end
  end

  def toggle_read
    if do_toggle_read
      head :ok # AJAX
    end
  end

  def toggle_acquired
    @issue = current_user.issue_data_by_issue_id(params[:id])
    unless @issue.nil?
      @issue.toggle!(:acquired)
      head :ok # AJAX
    else
      render :status => 500
    end
  end

  def toggle_track
    if current_user.tracked_issue?(params[:id])
      current_user.untrack_issue(params[:id])
    else
      current_user.track_issue(params[:id])
    end
    head :ok # AJAX
  end

  def batch_set
    byebug
    @op = params[:op]
    @ttag = params[:ttag]
    case @op
    when 'tracked'
      current_user.user_issues.where(issue_id: params[:ids].map{|id| id.to_i}).destroy_all
    when 'acquired'
      current_user.user_issues.where(issue_id: params[:ids].map{|id| id.to_i}).update_all(acquired: (params[:all_acquired].nil? ? false : true))
    when 'finished'
      current_user.user_issues.where(issue_id: params[:ids].map{|id| id.to_i}).update_all(finished: (params[:all_finished].nil? ? false : true))
    end
    respond_to do |format|
      format.js # AJAX
    end
end

  protected

  def do_toggle_read
    @issue = current_user.issue_data_by_issue_id(params[:id])
    unless @issue.nil?
      @issue.toggle!(:finished)
      return true
    else
      render :status => 500
      return false
    end
  end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_issue_row.html.haml
- cboxclass = (is_next_to_read ? '' : "dyn_checkbox")
%tr{id: (is_next_to_read ? "next_#{issue.series_id}" : '')}
  %td= check_box_tag("issue#{issue.id}", "tracked", current_user.tracked_issue?(issue.id), :class => cboxclass+' tracked', 'data-remote' => true, 'data-method' => 'get', 'data-url' => issues_track_path(issue.id) )
  %td= check_box_tag("issue#{issue.id}", "acquired", current_user.issue_acquired?(issue), :class => cboxclass+' acquired', 'data-remote' => true, 'data-method' => 'get', 'data-url' => issues_acquire_path(issue.id))
  %td= check_box_tag("issue#{issue.id}", "finished", current_user.issue_read?(issue), :class => cboxclass+' finished', 'data-remote' => true, 'data-method' => 'get', 'data-url' =>  is_next_to_read ? issues_next_read_path(issue.id) : issues_read_path(issue.id))
  %td
    = link_to "#{issue.series.name} - Issue ##{issue.number} - #{issue.title}", issues_view_path(issue.id)
    = " [#{issue.page_count.to_i} pages]"
  %td= issue.publication_date

app/views/issues/_list.html.haml
%table{id: (defined?(ttag) ? ttag : ''), style: 'margin-left:30px'}
  - unless is_next_to_read
    - @issue_ids = issues.map{|iss| iss.id}
    %b{style: 'margin-left:30px'}= 'Mark all:'
    %tr
      %td= check_box_tag("all_tracked", "tracked", true, 'data-remote' => true, 'data-method' => 'post', 'data-url' => issues_set_path, 'data-params' => {op: :tracked, ids: @issue_ids, ttag: ttag }.to_param )
      %td= check_box_tag("all_acquired", "acquired", false, 'data-remote' => true, 'data-method' => 'post', 'data-url' => issues_set_path, 'data-params' => {op: :acquired, ids: @issue_ids, ttag: ttag}.to_param )
      %td= check_box_tag("all_finished", "finished", false, 'data-remote' => true, 'data-method' => 'post', 'data-url' => issues_set_path, 'data-params' => {op: :finished, ids: @issue_ids, ttag: ttag}.to_param )
  %tr
    %th Tracked?
    %th Acquired?
    %th Read?
    %th Issue
    %th Pub. date
  - issues.each do |issue|
    - next unless issue.variant_of_id.nil?
    = render partial: 'issues/issue_row', locals: {issue: issue, is_next_to_read: is_next_to_read}

:javascript
  $(document).ready(function() {
      function update_all_toggles() {
        var ttag = "#{defined?(ttag) ? ttag : ''}";
        if(ttag != "") {
          ['acquired', 'finished'].forEach(function(klass) {
            if($('#'+ttag+' input.'+klass).length > 0) {
              all_true = true;
              $('#'+ttag+' input.'+klass).each(function() {
                if($(this).prop('checked') == false)
                  all_true = false;
              })
              if(all_true)
                $('#'+ttag+' input#all_'+klass).prop('checked',true);
            }
          });
        }
      };

    $('.dyn_checkbox').unbind('ajax:success')
        .bind("ajax:success", function(evt, xhr, settings) { update_all_toggles(); $(this).parent().append('<span id="fademe" class="ajax_success">saved!</span>'); $('#fademe').fadeOut(2000);});
    $('.dyn_checkbox').unbind('ajax:error')
        .bind("ajax:error", function(evt, xhr, settings) { update_all_toggles(); $(this).parent().append('<span id="fademe" class="ajax_error">error! :(</span>'); $('#fademe').fadeOut(5000);});
    update_all_toggles();
  });

app/views/issues/list.html.haml
%h1 Issues#list
%p Find me in app/views/issues/list.html.haml

app/views/issues/read.html.haml
%h1 Issues#read
%p Find me in app/views/issues/read.html.haml

app/views/issues/read_next.js.erb
parent = $("#next_<%= @issue.series_id %>").parent();
$("#next_<%= @issue.series_id %>").fadeOut(500, function() {
    $("#next_<%= @issue.series_id %>").remove();
    parent.append("<%= escape_javascript(render partial: 'issues/issue_row', locals: {issue: @issue, is_next_to_read: true}) %>");
  }
);

app/views/issues/search_by_series_and_writer.html.haml
.container-fluid
  %h1= "Writer search results in series #{@series.name}"

  %p= "These are issues containing something written by someone whose name contains '#{params[:writer]}':"
  != render(:partial => "list", :locals => {:issues => @issues, is_next_to_read: false, ttag: 'search_writer' })

  / != paginate @issues

app/views/issues/search_by_writer.html.haml
.container-fluid
  %h1 Writer search results
  %h2 by series
  - unless @series.empty?
    %table
      %tbody
        %tr
          %th Name
          %th Lang
          %th Published
          %th Publisher
          %th Country
          %th Issues by this writer
          %th Actions
        - @series.each do |series, count|
          %tr
            %td= link_to series.name, series_view_path(series.id)
            %td= series.language.code
            %td= (series.publication_dates.nil? or series.publication_dates.empty?) ? "#{series.year_began or '?'}-#{series.year_ended or '?'}" : series.publication_dates
            %td= series.publisher.name.length > 15 ? series.publisher.name[0..14]+'...' : series.publisher.name
            %td= series.country.name
            %td= link_to count.to_s, issues_search_by_series_and_writer_path(series: series.id, writer: params[:q])
            %td
              - if @current_user && @current_user.follows(series)
                = link_to 'Unfollow!', series_unfollow_path(series.id)
              - else
                = link_to 'Follow!', series_follow_path(series.id)
  %h2 by issues

  %p= "These are issues containing something written by someone whose name contains '#{params[:q]}':"
  != render(:partial => "list", :locals => {:issues => @issues, is_next_to_read: false, ttag: 'search_writer' })

  != paginate @issues

app/views/issues/unacquired.html.haml
%h1 Unacquired Issues
!= render(:partial => 'list', :locals => {:issues => @issues, is_next_to_read: false, ttag: 'unacquired' })

!= paginate @issues

app/views/issues/unread.html.haml
%h1 Unread Issues
!= render(:partial => 'list', :locals => {:issues => @issues, is_next_to_read: false, ttag: 'unread'})

!= paginate @issues

app/views/issues/view.html.haml
%h1= "#{@issue.series.name} - Issue ##{@issue.number} - #{@issue.title}"
%p= "Published: #{@issue.publication_date}"
%p= "Page count: #{@issue.page_count.to_i}"
%h2 Contents
- stories = @issue.stories.order('sequence_number asc')
- unless stories.nil?
  %table
    %tr
      %th Title
      %th Genre
      %th Pages
      %th Script
      %th Pencils
      %th Inks
      %th Colors
      %th Letters
      %th Editing
    - stories.each do |story|
      %tr
        %td= "#{story.feature} - #{story.title}"
        %td= story.genre
        %td= story.page_count.to_i
        %td= story.script
        %td= story.pencils
        %td= story.inks
        %td= story.colors
        %td= story.letters
        %td= story.editing
      %tr{:colspan => '9'}
        %td
          %p
            %strong
              Synopsis:
            = story.synopsis
          %p
            %strong
              Characters:
            = story.characters
          %hr