config/routes.rb
Methodicomic::Application.routes.draw do
  get "issues/list"
  get "issues/:id/view" => 'issues#view', as: 'issues_view'
  get "issues/:id/read" => 'issues#toggle_read', as: 'issues_read'
  get "issues/:id/read_next" => 'issues#read_next', as: 'issues_next_read'
  get "issues/:id/acquire" => 'issues#toggle_acquired', as: 'issues_acquire'
  get "issues/:id/track" => 'issues#toggle_track', as: 'issues_track'
  get "issues/unread"
  get "issues/unacquired"
  get "issues/search_by_writer"
  get "issues/search_by_series_and_writer"
  post "issues/set" => 'issues#batch_set', as: 'issues_set'
  get "series/search"
  get "series/list"
  get "series/:id/view" => 'series#view', as: 'series_view'
  get "series/:id/follow" => 'series#follow', as: 'series_follow'
  get "series/:id/unfollow" => 'series#unfollow', as: 'series_unfollow'
  get "session/create"
  get "welcome/index"
  get "welcome/login"
  match '/auth/:provider/callback', to: 'session#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'session#destroy', as: 'signout', via: [:get, :post]

  root 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def login
    redirect_to '/auth/google_oauth2'
  end

  def index
    @user = current_user
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_dashboard.html.haml
.row
  .col-lg-6.col-sm-12
    %h2 Series followed
    To track another series, enter a word to search for:
    = form_tag series_search_path, method: 'get' do
      = text_field_tag :q, nil, placeholder: 'e.g. Hellblazer'
      = submit_tag 'Search'
    You are currently tracking the following series:
    - if @user.tracked_series.nil?
      %p
        %em Absolutely none! :)
    - else
      != render(:partial => "series/list", :locals => {:series_list => @user.tracked_series })
    %h2 Find by Writer
    Type in a name to find issues containing texts authored by someone with that name.
    = form_tag issues_search_by_writer_path, method: 'get' do
      = text_field_tag :q, nil, placeholder: 'e.g. Alan Moore'
      = submit_tag 'Search'
  .col-lg-6.col-sm-12
    %h2 Issues tracked
    - if @user.tracked_issues.nil?
      %p
        %em You're tracking no issues at all!
    - else
      You are currently tracking
      %strong
        = @user.tracked_issues.count
      issues, of which you are yet to acquire
      %strong
        = link_to @user.unacquired_issue_count.to_s, issues_unacquired_path
      and yet to read
      %strong
        = link_to @user.unread_issue_count.to_s, issues_unread_path
      = '.'
      %h3 Next issue to read, by series
      != render(:partial => 'issues/list', :locals => {:issues => @user.first_unread_issues, is_next_to_read: true})
      %p{style: 'margin-left:30px'}
        = link_to 'More unread issues...', issues_unread_path
      %h3 Newest issues to acquire
      != render(:partial => 'issues/list', :locals => {:issues => @user.unacquired_issues.order(key_date: :desc).limit(10), is_next_to_read: false, ttag: 'new_unacquired'})
      %p{style: 'margin-left:30px'}
        = link_to 'More issues to acquire...', issues_unacquired_path
      %h3 Oldest issues to acquire
      != render(:partial => 'issues/list', :locals => {:issues => @user.unacquired_issues.order(key_date: :asc).limit(10), is_next_to_read: false, ttag: 'old_unaquired'})
      %p{style: 'margin-left:30px'}
        = link_to 'More issues to acquire...', issues_unacquired_path

app/views/welcome/index.html.haml
.container-fluid
  .row
    #title{style: 'margin:auto'}
      %h1
        %b The Methodic Comic
  %hr
  - if @user.nil?
    .row
      .col-md-12
        %h2 Track your comic book reading against the Grand Comics Database!
        %p The service lets you track series and individual issues and mark acquisition and reading progress at the level of the individual issue.
        %p Additional features may be added according to user requests.
        %h3 Please log in above (Google ID required, for now)
        %p Google's service is used out of laziness only; your e-mail or name are not actually used anywhere, and will never be given out.  This service will forever remain completely free, without ads.
  - else
    != render(:partial => "dashboard")

app/views/welcome/login.html.haml
%h1 Welcome#login
%p Find me in app/views/welcome/login.html.haml